:wrench: modified variables

diff --git a/scripts/certbot-create-cert b/scripts/certbot-create-cert
--- a/scripts/certbot-create-cert
+++ b/scripts/certbot-create-cert
@@ -3,36 +3,36 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name DOMAIN EMAIL" >&2
+  echo "${script_name}: usage: ${script_name} DOMAIN EMAIL" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "2" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "2" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-domain="$1"
-email="$2"
-docker_compose_dir="$(realpath "$script_dir/..")"
-docker_compose_filepath="$docker_compose_dir/docker-compose.yml"
+domain="${1}"
+email="${2}"
+docker_compose_dir="$(realpath "${script_dir}/..")"
+docker_compose_filepath="${docker_compose_dir}/docker-compose.yml"
 
-if ! docker-compose -f "$docker_compose_filepath" \
+if ! docker-compose -f "${docker_compose_filepath}" \
   exec certbot certbot certonly \
   --webroot \
   -w /var/www/certbot \
-  -d "$domain" \
-  --email "$email" \
+  -d "${domain}" \
+  --email "${email}" \
   --rsa-key-size 4096 \
   --agree-tos \
   --non-interactive; then
-  exit_with_error "failed to create https certificate to $domain"
+  exit_with_error "failed to create https certificate to ${domain}"
 fi
diff --git a/scripts/nginx-basic-auth b/scripts/nginx-basic-auth
--- a/scripts/nginx-basic-auth
+++ b/scripts/nginx-basic-auth
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name USERNAME PASSWORD" >&2
+  echo "${script_name}: usage: ${script_name} USERNAME PASSWORD" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "2" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "2" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-username="$1"
-password="$2"
+username="${1}"
+password="${2}"
 
-root_dir="$(realpath "$script_dir/..")"
-htpasswd_file="$root_dir/nginx/htpasswd"
+root_dir="$(realpath "${script_dir}/..")"
+htpasswd_file="${root_dir}/nginx/htpasswd"
 
-docker run --rm --entrypoint htpasswd httpd:2 -Bbn "$username" "$password" | sed '/^$/d' >>"$htpasswd_file"
+docker run --rm --entrypoint htpasswd httpd:2 -Bbn "${username}" "${password}" | sed '/^${/d}' >>"${htpasswd_file}"
diff --git a/scripts/nginx-config-plain b/scripts/nginx-config-plain
--- a/scripts/nginx-config-plain
+++ b/scripts/nginx-config-plain
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name DOMAIN" >&2
+  echo "${script_name}: usage: ${script_name} DOMAIN" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "1" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "1" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-domain="$1"
+domain="${1}"
 
-if ! "$script_dir/validate-domain" "$domain"; then
-  exit_with_error "not a valid domain '$domain'"
+if ! "${script_dir}/validate-domain" "${domain}"; then
+  exit_with_error "not a valid domain '${domain}'"
 fi
 
 cat <<EOF
@@ -31,7 +31,7 @@ server {
   listen 80;
   listen [::]:80;
 
-  server_name $domain;
+  server_name ${domain};
 
   location /.well-known/acme-challenge/ {
     root /var/www/certbot;
diff --git a/scripts/nginx-config-proxy b/scripts/nginx-config-proxy
--- a/scripts/nginx-config-proxy
+++ b/scripts/nginx-config-proxy
@@ -3,32 +3,32 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name DOMAIN" >&2
+  echo "${script_name}: usage: ${script_name} DOMAIN" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "2" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "2" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-domain="$1"
-proxy="$2"
+domain="${1}"
+proxy="${2}"
 
-if ! "$script_dir/validate-domain" "$domain"; then
-  exit_with_error "not a valid domain '$domain'"
+if ! "${script_dir}/validate-domain" "${domain}"; then
+  exit_with_error "not a valid domain '${domain}'"
 fi
 
-if ! "$script_dir/validate-http-url" "$proxy"; then
-  exit_with_error "not a valid proxy '$proxy'"
+if ! "${script_dir}/validate-http-url" "${proxy}"; then
+  exit_with_error "not a valid proxy '${proxy}'"
 fi
 
 cat <<EOF
@@ -36,7 +36,7 @@ server {
   listen 80;
   listen [::]:80;
 
-  server_name $domain;
+  server_name ${domain};
 
   location /.well-known/acme-challenge/ {
     root /var/www/certbot;
@@ -49,10 +49,10 @@ server {
   listen 443 ssl http2;
   listen [::]:443 ssl http2;
 
-  server_name $domain;
+  server_name ${domain};
 
-  ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;
-  ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;
+  ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
+  ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
 
   client_max_body_size 0;
   client_body_buffer_size 128k;
@@ -64,7 +64,7 @@ server {
   }
 
   location / {
-    proxy_pass          $proxy;
+    proxy_pass          ${proxy};
     proxy_http_version  1.1;
     proxy_cache_bypass  \$http_upgrade;
 
diff --git a/scripts/nginx-reload b/scripts/nginx-reload
--- a/scripts/nginx-reload
+++ b/scripts/nginx-reload
@@ -3,30 +3,30 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name" >&2
+  echo "${script_name}: usage: ${script_name}" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "0" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "0" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-if ! "$script_dir/nginx-test"; then
+if ! "${script_dir}/nginx-test"; then
   exit_with_error "failed to test nginx config"
 fi
 
-docker_compose_dir="$(realpath "$script_dir/..")"
-docker_compose_filepath="$docker_compose_dir/docker-compose.yml"
+docker_compose_dir="$(realpath "${script_dir}/..")"
+docker_compose_filepath="${docker_compose_dir}/docker-compose.yml"
 
-if ! docker-compose -f "$docker_compose_filepath" exec nginx nginx -s reload; then
+if ! docker-compose -f "${docker_compose_filepath}" exec nginx nginx -s reload; then
   exit_with_error "failed to reload nginx"
 fi
diff --git a/scripts/validate-domain b/scripts/validate-domain
--- a/scripts/validate-domain
+++ b/scripts/validate-domain
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name DOMAIN" >&2
+  echo "${script_name}: usage: ${script_name} DOMAIN" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "1" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "1" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-validate_regex="$script_dir/validate-regex"
+validate_regex="${script_dir}/validate-regex"
 regex_domain="^([a-z0-9-]{1,63}\.)+[a-z]{2,63}$"
-domain="$1"
+domain="${1}"
 
-if ! "$validate_regex" "$regex_domain" "$domain"; then
-  exit_with_error "not a valid domain '$domain'"
+if ! "${validate_regex}" "${regex_domain}" "${domain}"; then
+  exit_with_error "not a valid domain '${domain}'"
 fi
diff --git a/scripts/validate-email b/scripts/validate-email
--- a/scripts/validate-email
+++ b/scripts/validate-email
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name EMAIL" >&2
+  echo "${script_name}: usage: ${script_name} EMAIL" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "1" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "1" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-validate_regex="$script_dir/validate-regex"
+validate_regex="${script_dir}/validate-regex"
 regex_email="^[a-z0-9+_.-]+@[a-z0-9.-]+$"
-email="$1"
+email="${1}"
 
-if ! "$validate_regex" "$regex_email" "$email"; then
-  exit_with_error "not a valid email '$email'"
+if ! "${validate_regex}" "${regex_email}" "${email}"; then
+  exit_with_error "not a valid email '${email}'"
 fi
diff --git a/scripts/validate-http-url b/scripts/validate-http-url
--- a/scripts/validate-http-url
+++ b/scripts/validate-http-url
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
-script_dir="$(realpath "$(dirname "$0")")"
+script_name="$(basename "${0}")"
+script_dir="$(realpath "$(dirname "${0}")")"
 
 usage() {
-  echo "$script_name: usage: $script_name HTTP_URL" >&2
+  echo "${script_name}: usage: ${script_name} HTTP_URL" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "1" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "1" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-validate_regex="$script_dir/validate-regex"
-regex_url="https?://[^ ]+"
-url="$1"
+validate_regex="${script_dir}/validate-regex"
+regex_url="^https?://[^ ]+$"
+url="${1}"
 
-if ! "$validate_regex" "$regex_url" "$url"; then
-  exit_with_error "not a valid url '$url'"
+if ! "${validate_regex}" "${regex_url}" "${url}"; then
+  exit_with_error "not a valid url '${url}'"
 fi
diff --git a/scripts/validate-regex b/scripts/validate-regex
--- a/scripts/validate-regex
+++ b/scripts/validate-regex
@@ -3,27 +3,27 @@
 set -e
 set -u
 
-script_name="$(basename "$0")"
+script_name="$(basename "${0}")"
 
 usage() {
-  echo "$script_name: usage: $script_name REGEX VALUE" >&2
+  echo "${script_name}: usage: ${script_name} REGEX VALUE" >&2
 }
 
 exit_with_error() {
-  echo "$script_name: error: $1" >&2
+  echo "${script_name}: error: ${1}" >&2
   usage
   exit 1
 }
 
-if [ "$#" != "2" ]; then
-  exit_with_error "invalid number of arguments $#"
+if [ "${#}" != "2" ]; then
+  exit_with_error "invalid number of arguments ${#}"
 fi
 
-regex="$1"
-value="$2"
+regex="${1}"
+value="${2}"
 
-if [[ ! "$value" =~ $regex ]]; then
-  exit_with_error "value '$value' failed to match pattern '$regex'"
+if [[ ! "${value}" =~ ${regex} ]]; then
+  exit_with_error "value '${value}' failed to match pattern '${regex}'"
 fi
 
 exit 0
