:sparkles: finished scripts

diff --git a/scripts/nginx-test b/scripts/nginx-test
--- a/scripts/nginx-test
+++ b/scripts/nginx-test
@@ -1,11 +1,25 @@
 #!/usr/bin/env bash
-script_name="$0"
+
+script_name="$(basename "$0")"
 script_dir="$(realpath "$(dirname "$0")")"
+
+usage() {
+  echo "$script_name: usage: $script_name" >&2
+}
+
+exit_with_error() {
+  echo "$script_name: error: $1" >&2
+  usage
+  exit 1
+}
+
+if [ "$#" != "0" ]; then
+  exit_with_error "invalid number of arguments $#"
+fi
+
 docker_compose_dir="$(realpath "$script_dir/..")"
 docker_compose_filepath="$docker_compose_dir/docker-compose.yml"
 
 if ! docker-compose -f "$docker_compose_filepath" exec nginx nginx -t; then
-  exit 1
+  exit_with_error "failed to test nginx config"
 fi
-
-exit 0
